name: Label issues

on:
  issues:
    types:
      - opened
      - edited

jobs:
  add_Bug_Label:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bugKeyWords: [
          "Bug", "bug",
          "fix", "Fix",
          "doesn't work",
          "wrong", "Wrong",
          "Issue", "issue",
          "error", "Error",
          "crash", "Crash"
        ]
    permissions:
            issues: write
    steps:
      - uses: actions/checkout@v2
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        if: ${{contains(github.event.issue.title, matrix.featureKeyWords) || contains(github.event.issue.body, matrix.featureKeyWords)}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: bug

  add_Feature_Label:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        featureKeyWords: [
          "implement", "Implement", 
          "add", "Add", 
          "feature", "Feature",
          "enhancement", "Enhancement",
          "support", "Support",
          "wish", "Wish",
          "would like", "Would like", "Would Like",
          "improvement", "Improvement"
        ]
    permissions:
            issues: write
    steps:
      - uses: actions/checkout@v2
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        if: ${{contains(github.event.issue.title, matrix.featureKeyWords) || contains(github.event.issue.body, matrix.featureKeyWords)}}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: feature
            